code --install-extension aaron-bond.better-comments
code --install-extension amatiasq.sort-imports
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dline.CobaltNext
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension johnpapa.Angular2
code --install-extension miclo.sort-typescript-imports
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension PKief.material-icon-theme
code --install-extension roblourens.unittest-navigate
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Zignd.html-css-class-completion